dist: trusty
sudo: required
services: 
  - docker

language: go

jobs:
  include:
    - stage: build image
      name: "build image and push to quay.io/odo-dev/init-image-pr"
      script:
        - ./scripts/build-push-image.sh 
    - stage: test
      name: "core beta, java, source e2e tests"
      script:
        - ./scripts/testing.sh
        - cd $GOPATH/src/github.com/openshift/odo
        - ./scripts/oc-cluster.sh
        - oc login -u developer
        - make goget-tools
        - make bin
        - sudo cp odo /usr/bin/odo
        - travis_wait make test-e2e-beta
        - travis_wait make test-e2e-java
        - travis_wait make test-e2e-source
        - odo logout

    # Run a few odo integration tests
    - stage: test
      name: "generic, login, component command integration tests"
      script:
        - ./scripts/testing.sh
        - cd $GOPATH/src/github.com/openshift/odo
        - ./scripts/oc-cluster.sh
        - oc login -u developer
        - make goget-tools
        - make bin
        - sudo cp odo /usr/bin/odo
        - travis_wait make test-generic
        - travis_wait make test-cmd-login-logout
        - travis_wait make test-cmd-cmp
        - odo logout

    - stage: test
      name: "preference, config and url command integration tests"
      script:
        - ./scripts/testing.sh
        - cd $GOPATH/src/github.com/openshift/odo
        - ./scripts/oc-cluster.sh
        - oc login -u developer
        - make goget-tools
        - make bin
        - sudo cp odo /usr/bin/odo
        - travis_wait make test-cmd-pref-config
        - travis_wait make test-cmd-url
        - odo logout

    - stage: test
      name: "watch, storage, app and push command integration tests"
      script:
        - ./scripts/testing.sh
        - cd $GOPATH/src/github.com/openshift/odo
        - ./scripts/oc-cluster.sh
        - oc login -u developer
        - make goget-tools
        - make bin
        - sudo cp odo /usr/bin/odo
        - travis_wait make test-cmd-watch
        - travis_wait make test-cmd-storage
        - travis_wait make test-cmd-app
        - travis_wait make test-cmd-push
        - odo logout

    - stage: test
      name: "service, link, component sub-commands command integration tests"
      script:
        - ./scripts/testing.sh
        - cd $GOPATH/src/github.com/openshift/odo
        - ./scripts/oc-cluster.sh service-catalog
        - oc login -u developer
        - make goget-tools
        - make bin
        - sudo cp odo /usr/bin/odo
        - travis_wait make test-cmd-service
        - make test-cmd-link-unlink
        - travis_wait make test-cmd-cmp-sub
        - odo logout
